### ISSUE TITLE
5-Fold cross validation score computed on the full data set instead of training data

### ISSUE THREAD

**Issue by setare92-ha** [learn-co-curriculum/dsc-gradient-boosting-lab#2]
## Issue Subtype

- [ ] Master branch code
- [x ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

At the very end (right before the Summary section), the 5-fold cross validation is computed on the full data frame instead of being computed on the training dataset alone and the expected output sections (written as comments) are not correct. 

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for bringing this to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
We are in the process of updating this, so when we get there, we'll take your suggestion into account. Thank you again.
